name: beaten_beat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  universal_html: ^2.2.4
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica_Black_Oblique.otf
